# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.195.0/containers/rust/.devcontainer/base.Dockerfile
# [Choice] Debian OS version (use bullseye on local arm64/Apple Silicon): buster, bullseye
ARG VARIANT="bullseye"
FROM mcr.microsoft.com/vscode/devcontainers/rust:1-${VARIANT}

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt autoremove -y \
    && rustup toolchain install nightly \
    && rustup override set nightly \
    && rustup component add rustfmt clippy rust-analyzer \
    && curl -L https://raw.githubusercontent.com/rust-lang/rustlings/main/install.sh | bash
